<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $table = 'item';
    protected $fillable = [
        'Item_Code',
        'Barcode',
        'Barcode2',
        'Dispenser_Code',
        'NameTH',
        'NameEN',
        'Name2',
        'MyDescription',
        'CategorySub_Code',
        'St_Code',
        'Grp_1',
        'Brand_Code',
        'Color_Code',
        'Unit_Code',
        'Grade_Code',
        'Smell_Code',
        'Stuff_Code',
        'Size_Code',
        'Create_Code',
        'Create_DateTime',
        'Modify_Code',
        'Modify_DateTime',
        'zero',
        'row_count',
        'xMul',
        'Cost_Price',
        'SaleVolume',
        'SalePrice',
        'SalePrice1',
        'SalePrice2',
        'SalePrice3',
        'SalePrice4',
        'UnitAlt_Code',
        'MultiplierValue',
        'SaleAltPrice',
        'SaleAltPrice1',
        'SaleAltPrice2',
        'SaleAltPrice3',
        'SaleAltPrice4',
        'IsStock',
        'IsPurchase',
        'IsSale',
        'IsManufacturing',
        'IsCancel',
        'StockMin',
        'StockMax',
        'StockMovement',
        'EXP_Date',
        'Rate',
        'No',
        'ForeColor',
        'ItemM_Code',
        'Size_Alt_Code',
        'Production_Size_Code',
        'IsNewProduct',
        'ItemManufacturingNo',
        'IsChangeBucket',
        'isItemOrder',
        'DefaultUnitCode',
        'NameAcc',
        'BarcodeAcc',
        'Size_CodeAcc',
        'NamePr',
        'Unit_CodeAcc',
        'Unit_CodeFreeAcc',
        'Status_Group',
        'MaterialCode',
        'Temperature',
        'CheckStockMin',
        'IsDispenser',
        'isHidden',
        'Matter_code',
        'Ph_code',
        'Item_Group_Id',
        'ExamplePrice',
        'ExampleAltPrice',
        'RegisteredName',
        'Classify1',
        'Classify2',
        'Classify3',
        'Classify4',
        'IsSet',
        'IsPresent',
        'IsBoi',
        'ClassRowId',
        'IsConfirmBOI',
        'IsCms',
        'IsDealerActive',
        'Classify5',
        'UpdateBoiDate',
        'IsExample',
        'Package_size',
    ];
}
